
# Taller 1 - Métodos Numéricos
## 2020 - 2do cuatrimestre
### Objetivo

El objetivo del trabajo es completar los siguientes puntos relacionados con los temas de factorización LU, de Cholesky y matrices ortogonales. 

La idea es ejercitar tanto los conceptos teóricos como poder llevarlos a la práctica usando `numpy`

#### Evaluación:

- Implementar cada uno de los siguientes ejercicios, haciendo que corran los respectivos tests.

- Coloquio con los docentes durante la clase (preguntas sobre el enunciado y el código). Justificar las respuestas


# Ejercicio 0
## Precalentamiento en Numpy

En estos ejercicios vamos a trabajar un poco con `numpy` para afianzar su uso en para lo que viene luego.

Arranquemos con algunos fáciles:

### 0.1.1: Creación de matriz

Crear la siguiente matriz usando [`np.array`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html), consultar su tipo y dimensión.

$$
A =
\begin{pmatrix}
	1 & 2 & 3 \\
    4 & 5 & 6 \\
	7 & 8 & 9
\end{pmatrix}
$$



In [1]:
import numpy as np


"""
TODO: Crear matriz A
"""
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(type(A))
print(A.dtype)
print(A.shape)

<class 'numpy.ndarray'>
int64
(3, 3)


### 0.1.2: Creación de matriz nula

Crear una matriz de ceros de $\mathbb{R}$<sup>$3\times3$</sup>. 

**Nota:** Usar la función [np.zeros](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html)

In [2]:
"""
TODO: Crear matriz de ceros
"""

B = np.zeros(shape=(3,3))

assert(B.shape == (3, 3))
B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 0.1.3: Creación de matriz identidad

Crear una matriz identidad de $\mathbb{R}$<sup>$3 \times 3$</sup>.

**Nota:** Usar la función [np.eye](https://docs.scipy.org/doc/numpy/reference/generated/numpy.eye.html).


In [3]:
"""
TODO: Crear matriz identidad
"""
B = np.eye(3)

B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 0.1.4: Iterar sobre una matriz

Imprimir cada elemento de la matriz A (de izquierda a derecha, de arriba hacia abajo)

Usar [range](https://docs.python.org/3.6/library/stdtypes.html#typesseq-range) y [np.shape](https://docs.python.org/3.6/library/stdtypes.html#typesseq-range)

In [4]:
"""
TODO: Completar 
"""

for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        print(f"A[{i}, {j}] --> {A[i][j]}")

A[0, 0] --> 1
A[0, 1] --> 2
A[0, 2] --> 3
A[1, 0] --> 4
A[1, 1] --> 5
A[1, 2] --> 6
A[2, 0] --> 7
A[2, 1] --> 8
A[2, 2] --> 9


### 0.2: Operaciones

Vamos a hacer algunas operaciones sobre matrices. Sean $A$ y $B$ las siguientes matrices:

In [5]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [1, 1, 1],
    [0, 1, 1],
    [0, 0, 1]
])

### 0.2.1 Suma de matrices

Calcular $C = A + B$

In [9]:
"""
TODO: Completar código
"""

#Método 1: iterativamente

C = np.zeros((3, 3), dtype=int)

for row in range(A.shape[0]):
    for col in range(A.shape[1]):
        C[row, col] = A[row, col] + B[row, col]

print(C)
# Método 2: vectorialmente (mucho mejor!)
C = A+B
print(C)

[[ 2  3  4]
 [ 4  6  7]
 [ 7  8 10]]
[[ 2  3  4]
 [ 4  6  7]
 [ 7  8 10]]


### 0.2.1 Multiplicación de matrices

Calcular $C = A B$.

**Nota:** Ver documentación de [np.matmul](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul) (función que implementa el operador `@`).

In [12]:
"""
TODO: Calcular el producto de A y B
"""

# Método 1

C = np.zeros((3, 3), dtype=int)

for row in range(C.shape[0]):
    for col in range(C.shape[1]):
        for i in range(A.shape[1]):
            C[row, col] += A[row, i]* B[i, col]

print(C)
# Método 2: mejor
C = A @ B
print(C)

assert(np.allclose(C, np.array([
    [1, 3, 6],
    [4, 9, 15],
    [7, 15, 24]
])))

[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


### 0.3: Igualdad de matrices:





![alt text](https://pm1.narvii.com/5991/b3ff9d95cc8cd7916b1d1b432fcd3bf79b6a62e2_hq.jpg)

**Nota**: Para los que no hayan visto "Indiana Jones y la última Cruzada": el protagonista llega a un lugar protegido por un templario donde hay muchas copas, y sólo una es el "Santo Grial".

Pueden ver la secuencia acá: en [español](https://www.youtube.com/watch?v=-EvzYURFdR0&t=73s) o el [original](https://www.youtube.com/watch?v=A0TalLrtZ24&t=15s).




Acá, también tenemos que elegir sabiamente...


Sean dos matrices, $B$ y $C$, producto de distintos cálculos. ¿Cómo podemos verificar que son iguales?


In [13]:
A = np.array([
    [.1, 0, 0],
    [0, .1, 0],
    [0, 0, .1],
], dtype="float")

B = A + A + A

C = np.array([
    [.3, 0, 0],
    [0, .3, 0],
    [0, 0, .3],
], dtype="float")

Primero, imprimámoslas para ver qué tienen...

In [14]:
print(f"B = \n {B}")
print(f"C = \n{C}")


B = 
 [[0.3 0.  0. ]
 [0.  0.3 0. ]
 [0.  0.  0.3]]
C = 
[[0.3 0.  0. ]
 [0.  0.3 0. ]
 [0.  0.  0.3]]


¡Fantástico, todo parece andar bien! Veamos ahora si `B == C`

In [15]:
result = B == C

type(result)

numpy.ndarray

El resultado es un array, ya que `B == C` se efectúa elemento a elemento. 

No queremos eso. Podemos entonces hacer `(A == A.T).all()` que, dada una matriz de booleanos, verifica si todos sus elementos son `True`.

In [16]:
(B == C).all()

False

Las dos matrices son distintas? 😱

Hemos cometido uno de los pecados capitales de Métodos Numéricos: comparación por igualdad entre dos números de punto flotante.

![](https://media1.tenor.com/images/4988bf571adbd4edc5df437a8530eba4/tenor.gif?itemid=5056977 "chess")


### IMPORTANTE: NUNCA COMPARAR PUNTOS FLOTANTES POR IGUALDAD

Recordemos que, producto de la limitada precisión de estos números, siempre debemos comparar con cierta "tolerancia". `numpy` nos provee de una función que nos permite hacer esto: [np.allclose](https://docs.scipy.org/doc/numpy/reference/generated/numpy.allclose.html)

**Nota**: Si quieren entender un poco más algunas sutilezas de cómo Python maneja los puntos flotantes (más allá del estandar de la IEEE) pueden ver [este link](https://docs.python.org/3/tutorial/floatingpoint.html).

In [17]:
# Esto es lo mismo que hacer 
# np.isclose(B, C).all()
np.allclose(B, C)

True

¡Bien! Has elegido sabiamente, c

![](https://media1.tenor.com/images/c69f043088acef4637ecce5de0e3bed9/tenor.gif?itemid=13257298 "wisely")



### 0.3.1: Creación de matriz aleatoria

Crear una matriz de $\mathbb{R}$<sup>$3\times 3$</sup> uniformemente distribuida en el intervalo $(0, 1)$.

Usar [np.random.rand](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.rand.html)

In [24]:
A = np.random.rand(3,3)

A

array([[0.09424914, 0.42369076, 0.83610376],
       [0.6123728 , 0.76746297, 0.05723711],
       [0.75980776, 0.775633  , 0.24461907]])

### 0.3.2: Creación de matriz aleatoria con distribución $N(0, 1)$

Crear una matriz de $\mathbb{R}$<sup>$3\times3$</sup> tal que cada coordenada sea una variable con distribución $N(0, 1)$.

**Nota:** Usar la función [np.random.randn](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randn.html)

In [25]:
A = np.random.randn(3,3)

A

array([[ 0.56960876,  2.31177281,  0.4201651 ],
       [-0.58879613, -1.138712  ,  1.17228408],
       [ 0.29336591, -0.40664925, -1.58034417]])

### 0.4: Slicing (¿Rebanado?)

Dada la matriz

$$
A =
\begin{pmatrix}
	1 & 2 & 3 \\
    4 & 5 & 6 \\
	7 & 8 & 9
\end{pmatrix}
$$

Vamos a realizar diferentes accesos a las submatrices de $A$. 

**Observación**: `numpy` maneja de manera distinta los arrays 1-dimensionales de los n-dimensionales. Tener esto siempre en cuenta!


### 0.4.1 Obtener la segunda fila de la matriz


In [29]:
"""
TODO: Completar código
""" 
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

fila = A[1,:]
print(fila)
assert(np.allclose(fila, np.array([4, 5, 6])))

[4 5 6]


### 0.4.2 Obtener la tercera columna de A

In [30]:
columna = A[:,2]

assert(np.allclose(columna, np.array([3, 6, 9])))

### 0.4.3 Obtener submatriz

Obtener la submatriz

$$
\begin{pmatrix}
	1 & 2 \\
    4 & 5
\end{pmatrix}
$$

de la matriz $A$.


In [31]:
submatriz = A[0:2, 0:2]

assert(np.allclose(
    submatriz, 
    np.array([
       [1, 2],
       [4, 5]
    ])
))

### 0.5: Reshape:

Muchas veces ocurre que tenemos listas de números que queremos convertir en una matriz, o bien arrays de una dimensión (vectores) que queremos convertirlos en matrices fila/columna ya que `numpy` suele efectuar de manera distinta las operaciones en el caso 1-dimensional o 2-dimensional.

Para ello, aprenderemos a hacer darle una nueva "forma" al array. Para ello, utilizaremos la función [reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html) de `numpy`.


### 0.5.1: Lista a matriz
Convertir el array $L = [1, 2, \ldots, 7, 8, 9]$ en la matriz de $\mathbb{R}$<sup>$3 \times 3$</sup>

$$
A =
\begin{pmatrix}
	1 & 2 & 3 \\
    4 & 5 & 6 \\
	7 & 8 & 9
\end{pmatrix}
$$



**Sugerencia:** Verificar las dimensiones de las matrices y/o vectores usando [shape](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.ndarray.shape.html).

In [35]:
# range es un iterador ... para convertirlo en una lista concreta, hay que hacer esto

nums = list(range(1, 10))

L = np.array(nums)

"""
TODO: Completar código
"""
A = np.reshape(L, (3,3))


assert(np.allclose(
    A, np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])))

### 0.5.2: Vectores columna

1. ¿Qué nos da el `shape` de obtener la primera columna de $A$ con `A[:, 0]`?
2. Si `v = A[:, 0]` ¿cuál es el resultado de `v @ v.T`? ¿Por qué ocurre esto? (ver documentación de [np.matmul](https://numpy.org/devdocs/reference/generated/numpy.matmul.html?highlight=matmul#numpy.matmul))
3. Utilizar `reshape` para convertir `v` en una matriz columna de $\mathbb{R}$<sup>`3 x 1`</sup>
**Nota:** reshape permite utilizar `-1` como comodín.

In [36]:
v = A[:, 0]

print(v.shape)
print(v.shape == (1,3))
print(v.shape == (3,1))
print(v.shape == 3)


(3,)
False
False
False


In [37]:

"""
TODO: usar reshape para v como un vector columna
"""
mat_columna = v.reshape(3,1)


assert(mat_columna.shape == (3, 1))

### 0.6.1 Producto Interno

Calcular el producto interno entre la primera fila de $A$ y la tercera columna de $B$. 

**Nota:** Ver documentación de [np.dot](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul).

In [38]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [1, 1, 1],
    [0, 1, 1],
    [0, 0, 1]
])

""" 
TODO: Calcular el producto interno pedido
"""
prod_interno = A[0,:].reshape(1,3) @ B[:,2].reshape(3,1)

assert(np.isclose(prod_interno, 6))

### 0.6.2 Producto Externo

Sean $u = (1, 2, 3)$, $v = (-1, 1, 2)$ (primera fila, y última columna de A y B respectivamente). Calcular la matriz $u v^T$ (el llamado producto externo entre $u$ y $v$).

¿Cuál es el rango columna de $u v^T$?

**Nota**: puede realizarse haciendo un reshape y luego @, o bien usando [np.outer
](https://docs.scipy.org/doc/numpy/reference/generated/numpy.outer.html).



In [39]:

u = A[0, :]
v = B[:, 2]

print(u.shape, v.shape)

"""
TODO: Calcular el producto externo
"""
prod_externo = u.reshape(3,1) @ v.reshape(1,3)

assert(np.allclose(prod_externo, np.array([
    [1,  1,  1],
    [2,  2,  2],
    [3,  3,  3]]
)))


(3,) (3,)


## Ejercicio 1

Repasar la definición de factorización LU. ¿Bajo qué condiciones podemos garantizar
que una matriz inversible tiene factorización LU? 

Completar la función `tiene_LU` que dada una matriz A, nos devuelve `True` si tiene factorización LU, o `False` en caso contrario.

**Tip**: considerar las funciones [np.shape](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.ndarray.shape.html) para obtener las dimensiones de una matriz, y [np.linalg.det](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.linalg.det.html) para obtener el determinante de una matriz.


In [299]:
eps = 1e-6

def tiene_lu(A):
    """
    Dada una matriz A, devuelve True si tiene descomposición LU, o False en caso contrario
    
    Argumentos:
    -----------
    
    A: np.array
        Matriz de floats

    Devuelve:
    ---------
    
    res: bool
        True si tiene LU, False caso contrario
    """ 
    
    """
    TODO: Completar la función
    """
    
    '''
    Forma 1: Todos los determinantes de las submatrices != 0
    '''
    
    for row in range(1, A.shape[0]+1):
        A_aux = A[0:row, 0:row].reshape(row, row)
        if np.abs(np.linalg.det(A_aux)) < eps:
            return False
    
    return True

    '''
    Forma 2: Es estrictamente diagonal dominante
    '''
    
#     diagonal = np.diag(A)
#     for elem, row in zip(diagonal, A):
#         suma = np.sum(np.abs(row)) - 2*np.abs(elem)
#         if suma >= 0:
#             return False
#     return True


### Unittest

Corramos unos tests automatizados para ver si esto funciona. 

**PUEDEN SIMPLEMENTE IGNORAR ESTO**

**Obs 1**: A cada test le pondremos el decorador `@mntest` definido arriba. Necesitamos además setear en cada celda donde corramos tests la variable `tests` a `[]`.

**Obs 2**: No usaremos ninguna de las bibliotecas estándar de Python (`unittest` o `pytest`) puesto que no están pensadas para funcionar con Jupyter.

In [300]:
#Código para que corran los tests: (pueden ignorarlo)

import numpy as np
import math
import traceback


def mntest(func):
    global tests
    
    tests.append(func)    
    
    return func

def correr_tests():
    excepciones = []
    for test in tests:
        try:
            print("Corriendo {} ... ".format(test.__name__), end='')
            test()
            print("OK")
        except AssertionError as e:
            error_msg = traceback.format_exc()
            excepciones.append((test, error_msg))
            print("ERROR")
    
    if len(excepciones) > 0:
        print("\nErrores:\n")
        for (test, error_msg) in excepciones:
            print("En {}".format(test.__name__))
            print(error_msg)
    else:
        print("\n\nTodos los tests pasaron correctamente")

In [301]:
tests = []


@mntest
def testear_identidad_tiene_LU():
    A = np.identity(3)
        
    assert(tiene_lu(A))
    

@mntest
def testear_matriz_ceros_no_tiene_LU():
    A = np.zeros((3, 3))
        
    assert(not tiene_lu(A))
    
@mntest
def testear_matriz_no_inversible():
    A = np.ones((3, 3))
    
    assert(not tiene_lu(A))

@mntest 
def testear_matriz_permutacion_no_tiene_LU():
    A = np.array([
        [1, 0, 0],
        [0, 0, 1],
        [0, 1, 0]
    ])
    
    assert(not tiene_lu(A))


correr_tests()

Corriendo testear_identidad_tiene_LU ... OK
Corriendo testear_matriz_ceros_no_tiene_LU ... OK
Corriendo testear_matriz_no_inversible ... OK
Corriendo testear_matriz_permutacion_no_tiene_LU ... OK


Todos los tests pasaron correctamente


## Ejercicio 2: Resolver LU por bloques



### ¿Cómo era esto de resolver en bloques?
Sea $A \in \mathbb{R}^{n \times n}$ a la cual le queremos calcular la factorización LU. Para ello, lo calcularemos en bloques en vez del método tradicional de triangulación. 

Supongamos que A tiene factorización LU; es decir podemos descomponerla en $L, U \in \mathbb{R}^{n \times n}$ escribiendo la descomposición en bloques de la forma:


$$
A = L U \\
$$

$$
\begin{pmatrix}
a_{11}   & A_{12}  \\
A_{21} & A_{22}
\end{pmatrix} = \begin{pmatrix}
1 & 0  \\
L_{21} & L_{22}
\end{pmatrix} \begin{pmatrix}
u_{11}   & U_{12}  \\
0 & U_{22}
\end{pmatrix}
$$

&nbsp;


donde $a_{11}, l_{11}, u_{11}$ son escalares, $A_{12} \in \mathbb{R}^{1 \times (n-1)}$ (vector fila), $L_{21} \in \mathbb{R}^{(n-1) \times 1}$

De aquí obtenemos las siguientes ecuaciones:

\begin{align*}
u_{11} &= a_{11} \\
U_{12} &= A_{12} \\
L_{21} &= \frac{A_{21}}{u_{11}}  \\
\end{align*}

Estas 3 ecuaciones nos permitirán despejar y obtener el contenido de estos 3 bloques. Ahora, nos queda la última ecuación:

$$
A_{22} = L_{21} U_{12} + L_{22} U_{22} \\
$$

Reescribiéndola, nos queda:
$$
A_{22} - L_{21} U_{12} = L_{22} U_{22} \\
$$

Y aquí, un pequeño salto de fe (esperemos razonable para los que ya hayan cursado Algo 2): si resolvemos la factorización LU de $A_{22} - L_{21} U_{12}$, podemos obtener los dos bloques que nos faltan.





**Ejercicio**:  Calcular LU en bloques para que tome una matriz $A \in \mathbb{R}^{n \times n}$ y nos devuelva $L$ y $U$, su descomposición LU correspondiente. 

La resolución tiene que ser *iterativa* pero puede convenir empezar a pensarlo en términos recursivos.

**RESPONDER**: ¿Cómo aseguran paso a paso que la matriz tenga factorización LU?

**Respuesta**
Básicamente, estamos reduciendo la matriz por eliminación gaussiana. Asique si la matriz original tiene LU => todas las submatrices tienen LU. 

**Hint**: Ojo con la dimensión de los vectores. Si queremos multiplicar una matriz "columna", con una matriz "fila" tenemos que hacer reshape primero.

In [289]:
def lu_recursivo(A):
    current = A.copy()
    size = current.shape[0]
    if size == 1:
        return np.array([1]), current[0,0]
    
    A11 = current[0,0].reshape(1,1)
    A12 = current[0, 1:].reshape(1, size-1)
    A21 = current[1:, 0].reshape(size-1, 1)
    A22 = current[1:, 1:].reshape(size-1, size-1)
    
    U11 = A11
    U12 = current[0, 1:].reshape(1, size-1)
    U21 = np.zeros((size-1, 1))
    
    L11 = 1
    L12 = np.zeros((1, size-1))
    L21 =  A21 * (1/U11)

    new_A = A22 - (L21 @ U12)
    
    L22, U22 = lu_recursivo(new_A)
    
    return np.block([[L11, L12],[L21, L22]]), np.block([[U11, U12],[U21, U22]])
    

In [302]:
def lu_en_bloques(A):
    """
    Dada una matriz A, devuelve L, U 
    
    Argumentos:
    -----------
    
    A: np.array
        Matriz de floats

    Devuelve:
    ---------
    
    L, U: np.array
        Descomposición LU de A
        
    """
    
    """
    current_matrix es la matriz a la cual le estoy calculando LU
    
    Primero va a ser A, luego A22 - L21 * U21, ...
    """
    current_matrix = A.copy().astype('float64')
    
    """
    Vamos a ir "rellenando" paso a paso la factorización LU
    """
    L = np.zeros(A.shape, dtype='float64')
    U = np.zeros(A.shape, dtype='float64')
    
    n = A.shape[0]
    
    """
    Vamos a iterar desde 0 hasta n-1 e ir completando L y U
    de acuerdo a las ecuaciones antes explicadas
    """
    for i in range(n):
        """
        
        Observación: 
        
        En cada paso i estamos "llenando" las columnas y filas i-ésimas de L y U. Por eso tenemos que indexar por i
        
        Sin embargo, current_matrix la tenemos que indexar en 0 ya que es la matriz que vamos a ir
        "achicando" en dimensión. 
        
        """
        
        """
        TODO: Rellenar los valores de L[i, i] y U[i, i]
        """
        L[i, i] = 1
        U[i, i] = current_matrix[0,0]
        """
        Caso "base": si es el final, no seguir
        """
        if i == n-1:
            break
        
        """
        TODO: Calcular los nuevos valores de U12 y L21
        """
        U[i, i+1:] = current_matrix[0, 1:]
        L[i+1:, i] = current_matrix[1:, 0] * (1/U[i,i])
        
        """
        TODO: Calcular la matriz del caso "recursivo".
        
        Esto sería la nueva "A"
        
        Sugerencia: usar np.outer o hacer reshape
        """
        current_dim = current_matrix.shape[0]
        
        new_matrix =  current_matrix[1:, 1:].reshape(current_dim-1, current_dim-1)
        new_matrix -= L[i+1:, i].reshape(current_dim-1,1) @ U[i, i+1:].reshape(1, current_dim-1)#L21 * U12
        
        """
        Asignamos la nueva matriz a calcular LU
        
        Nos aseguramos de que su dimensión se haya reducido en uno
        """
        current_matrix = new_matrix
        assert(current_matrix.shape == (current_dim-1, current_dim-1))

    return L, U


In [304]:
tests = []


@mntest
def testear_con_multiplo_identidad():
    A = 3 * np.identity(3)
    
    #L, U = lu_en_bloques(A)
    L, U = lu_recursivo(A)
    
    assert(np.allclose(L, np.eye(3)))
    assert(np.allclose(U, 3*np.eye(3)))
    
    

@mntest
def testear_con_otra_matriz():
    L = np.array([
        [1, 0, 0],
        [1, 1, 0],
        [1, 1, 1],
    ])

    U = np.array([
        [1, 1, 1],
        [0, 2, 2],
        [0, 0, 3],
    ])

    A = L @ U
    
    #L1, U1 = lu_en_bloques(A)
    L1, U1 = lu_recursivo(A)
    
    assert(np.allclose(L1, L))
    assert(np.allclose(U1, U))

@mntest
def testear_con_otra_matriz2():
    A = np.array([
        [8, 2, 0],
        [4, 9, 4],
        [6, 7, 9],
    ])


    
    #L1, U1 = lu_en_bloques(A)
    L1, U1 = lu_recursivo(A)
    
    assert(np.allclose(L1@U1, A))

    

correr_tests()


Corriendo testear_con_multiplo_identidad ... OK
Corriendo testear_con_otra_matriz ... OK
Corriendo testear_con_otra_matriz2 ... OK


Todos los tests pasaron correctamente


## Ejercicio 3

Completar la función con un método para determinar si una matriz es ortogonal o no. 

En caso de serlo, explicar cómo se podría devolver un conjunto ortonormal de vectores a partir de la matriz.

**Agregar dos casos de test** probando con dos matrices ya conocidas: de rotaciones (Givens) y de reflexiones (Householder)

In [291]:
def es_ortogonal(A):
    """
    Devuelve True si A es ortogonal, False en otro caso
    
    
    Argumentos:
    ----------
    
    A: np.array
        
    Devuelve:
    ---------
    
    res: bool
        True si A ortogonal, False en otro caso
    """

    """
    TODO: Completar acá
    """
    '''
    Forma 1: Mantiene la norma
    '''
    
#     cols = A.shape[0]
    
#     x = np.random.rand(cols, 1)
#     norma_x = np.linalg.norm(x)
#     Ax = A @ x
#     norma_Ax = np.linalg.norm(Ax)
#     ret = np.isclose(norma_x, norma_Ax)
    
    '''
    Forma 2: Q^t*Q
    '''
    ret = np.allclose(A@A.T, np.eye(A.shape[0]))
    
    
    return ret

In [305]:
from math import cos, sin
tests = []

@mntest
def probar_con_identidad():
    A = np.eye(3)
    
    assert(es_ortogonal(A))
    
@mntest
def probar_con_rotacion():
    angle = math.pi/4
    """
    TODO: Escribir una matriz de rotación angle de 2x2 
    """
    A = np.array([[cos(angle), -sin(angle)],
                  [sin(angle), cos(angle)]])
    
    assert(es_ortogonal(A))

@mntest
def probar_con_reflexion():
    v = np.array([[1,1,1]], dtype='float64')
    """
    TODO: Escribir la matriz de reflexión sobre el plano cuya normal es v
    """
    v_norm = np.linalg.norm(v)
    v /= v_norm
    I = np.eye(3)
    A =  I - 2* (v.T @ v)
    assert(es_ortogonal(A))

    
correr_tests()

Corriendo probar_con_identidad ... OK
Corriendo probar_con_rotacion ... OK
Corriendo probar_con_reflexion ... OK


Todos los tests pasaron correctamente


## Ejercicio 4

Sea $A \in \mathbb{R}^{n \times n}$, simétrica y no singular

### Ejercicio 4.1

Si $A$ tiene factorización $LU$, probar que tiene factorización $LDL^T$. ¿Son las dos $L$ iguales? 

**Respuesta:**

\begin{align*}
A &= A^T \\
L U &= U^T L^T\\
U L^{-T} &= D\\
U &= D L^{T}\\
A &= L D L^{T}\\
\end{align*}

Las 2 $L$ son iguales.


#### SOLUCIÓN

Unas pequeñas pistas
Si $A = LU$ es simétrica, entonces 

\begin{align*}
A &= A^T \\
L U &= U^T L^T\\
\end{align*}

¿Qué forma tiene $U^T$? ¿Es el lado derecho una factorización LU? ¿Cómo la podemos convertir a una factorización LU? (sin calcular ninguna inversa, de ser posible)


**Respuesta**

$U^T$ es triangular inferior. El lado derecho no es una factorización LU porque $U^T$ no necesariamente tiene unos en la diagonal.

Para hacer la parte derecha LU, nos armamos una matriz diagonal con la diagonal de $U^T$. La inversa de esa matriz, también es diagonal y se consigue:
$$D^{-1}_{[i,i]} = \frac{1}{D_{[i,i]}}$$

Luego, ya que $D \cdot D^{-1} = I$ podemos reescribir:
$$U^T \cdot L^T = U^T \cdot D^{-1} \cdot D \cdot L^T$$

Si agrupamos podemos decir que:
\begin{align*}
(U')^{T} &= U^T \cdot D^{-1} \\
(L')^{T} &= D \cdot L^T\\
\end{align*}

Donde ahora $(U')^{T} \cdot (L')^{T}$ si es una factorización LU

### Ejercicio 4.2

Dada la factorización $A = LU$, ¿Cómo puedo calcular $D$ (de $LDL^T$) sin usar matrices inversas?



### SOLUCIÓN

Sabemos por el ejercicio 4.1 que:
$$D = U L^{-T}$$

También sabemos que la diagonal de $L$ es igual a la diagonal de $L^{-1}$, que también es igual a $L^T$ y a $L^{-T}$.

Por lo tanto, al ser $U$ y $L^{-T}$ triangulares superiores, y al solo estar interesados en la diagonal del resultado podemos decir que:

\begin{align*}
D_{[i,i]} &= U_{[i,i]} * L_{[i,i]} \\
D_{[i,i]} &= U_{[i,i]} * 1\\
D_{[i,i]} &= U_{[i,i]}\\
\end{align*}




### Ejercicio 4.3



Completar la función `chol_from_LU` para que tome una matriz A y devuelva la matriz correspondiente a su factorización de Cholesky utilizando como base la factorización LU de `A`, sin calcular ninguna matriz inversa en el medio.

En el caso de que la matriz no tenga factorización de Cholesky, **debe generar un error mediante `raise ValueError`**

    
**Hint**: considerar las funciones [np.diag](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.diag.html) y [np.sqrt](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.sqrt.html).

Dada una matriz `A` podemos obtener una matriz que tenga la diagonal de `A` y 0 en las demás posiciones mediante `np.diag(np.diag(A))`


In [306]:
def es_simetrica(A):
    """
    TODO: Completar esta función
    """
    return np.allclose(A, A.T)

def chol_from_lu(A):
    """
    Devuelve la L de Cholesky a través de la factorización LU de la matriz A
    
    En caso de que no tenga LU o que no tenga Cholesky, lanza ValueError
    
    Argumentos:
    ----------
    
    A: np.array
        Matriz a factorizar
    
    Devuelve:
    ---------
    
    L: np.array
        Factorización de Cholesky de A
    """
    if not es_simetrica(A):
        raise ValueError("Matriz no simétrica")
    
    
    L, U = lu_en_bloques(A)
    """
    TODO: Completar acá
    """
    diagonal = np.diag(U)
    if (diagonal<0).any():
        raise ValueError("No existe cholesky")
        
    diagonal = np.sqrt(diagonal)
    D_inversa = np.diag(diagonal)
    
    L_cholesky = L @ D_inversa
    
    
    return L_cholesky

In [307]:
tests = []


@mntest
def testear_con_identidad():
    A = np.eye(3)
    L = chol_from_lu(A)
    
    # Cholesky es la identidad también :-)
    assert(np.allclose(A, L))
    

@mntest
def testear_con_multiplo_identidad():
    A = 4 * np.eye(3)
    L = chol_from_lu(A)
    
    # Cholesky es la identidad también :-)
    assert(np.allclose(L, 2* np.eye(3)))
    
@mntest
def testear_con_matriz_no_sdp():
    A = np.array([
        [1, 0, 0],
        [0, -1, 0],
        [0, 0, 2]
    ])
    try:
        L = chol_from_lu(A)
        raise AssertionError("Tiene que lanzar excepción")
    except ValueError as e:
        pass

@mntest
def testear_con_matriz():
    L1 = np.array([
        [1, 0, 0],
        [2, 2, 0],
        [4, 4, 4]
    ])
    
    A = L1 @ L1.T
    L = chol_from_lu(A)
    assert(np.allclose(L, L1))

correr_tests()


Corriendo testear_con_identidad ... OK
Corriendo testear_con_multiplo_identidad ... OK
Corriendo testear_con_matriz_no_sdp ... OK
Corriendo testear_con_matriz ... OK


Todos los tests pasaron correctamente


## Ejercicio 5: Opcional

Supongamos que tenemos $A \in \mathbb{R}^{n \times n}$. Si generamos $x_1, \ldots x_k \in \mathbb{R}^n$ vectores aleatorios ¿cómo podemos chequear "probabilísticamente" que $A$ es simétrica definida positiva?

Enunciar un método basado en la generación de vectores aleatorios para mostrar que una matriz no es definida positiva o para ganar más confianza en que sí lo es. 

**Opcional**: Tratar de pensar la implementación sin for, ni while 

**Opcional 2**: ¿Se les ocurre algún ejemplo en el que fallaría este método?

El método puede fallar si los vectores se generan con valores positivos y para que $x^{T} \cdot A \cdot x <= 0$ se necesita al menos un elemento del vector negativo. Además si justo justo justo el vector aleatorio es un vector de ceros. Pero la probabilidad de que eso pase tiende a cero.

**Tip**: 
Las funciones [np.diagonal](https://docs.scipy.org/doc/numpy/reference/generated/numpy.diagonal.html) y [np.any](https://docs.scipy.org/doc/numpy/reference/generated/numpy.any.html) también pueden ser de ayuda.

In [308]:

def tiene_sdp_vectores_aleatorios(A, n):
    """
    Chequea que la matriz sea SDP usando método probabilístico de vectores aleatorios
    
    Argumentos:
    ----------
    
    A: np.array
        Matriz a verificar su condición de SDP
       
    n: int
        Cantidad de vectores a 
    
    Devuelve:
    ---------
    
    res: bool
        True si no encontró si A es SDP bajo este método probabilístico
    """
    if not es_simetrica(A):
        return False
    
    """
    TODO: Generar vectores aleatorios y verificar si alguno rompe la condición de DP
    """ 
    
    size = A.shape[0]
    v_aleatorios = np.random.uniform(low = -10, high = 10, size=(size, n))
    v_aleatorios_t = v_aleatorios.T
    
    res = (v_aleatorios_t @ A) @ v_aleatorios
    diagonal = np.diag(res).reshape(1, n)
    res = diagonal>0
    return res.all()

Con este ejemplo debería andar:

In [309]:
tests = []


@mntest
def testear_con_identidad():
    A = np.eye(3)
    assert(tiene_sdp_vectores_aleatorios(A, 10000))
    
    

@mntest
def testear_con_matriz_no_sdp():
    A = np.array([
        [1, 0, 0],
        [0, -1, 0],
        [0, 0, 1],
    ])
    
    assert(not tiene_sdp_vectores_aleatorios(A, 10000))
    
    
@mntest
def testear_con_otra_matriz_no_sdp():
    A = np.array([
        [1, 0, 0],
        [0, 1, 2],
        [0, 2, 1],
    ])
    
    assert(not tiene_sdp_vectores_aleatorios(A, 10000))
    
    

correr_tests()


Corriendo testear_con_identidad ... OK
Corriendo testear_con_matriz_no_sdp ... OK
Corriendo testear_con_otra_matriz_no_sdp ... OK


Todos los tests pasaron correctamente
